apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: your_php_image # Replace with your actual image name or build context
          ports:
            - containerPort: 80
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: php-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  ports:
    - port: 8080
  selector:
    app: php
